https://www.tensorflow.org/tutorials/quickstart/beginner

In [2]:
import tensorflow as tf

In [3]:
print("TF Version:", tf.__version__)

TF Version: 2.9.1


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


In [13]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10),

])

2022-07-19 08:35:26.023302: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [17]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.17965949,  0.05464501,  0.01860342, -0.0131684 ,  0.11689889,
         0.5138046 , -0.00374583,  0.31388518,  0.26364607, -0.1515722 ]],
      dtype=float32)

In [18]:
tf.nn.softmax(predictions).numpy()

array([[0.07447623, 0.09414014, 0.09080759, 0.08796783, 0.100187  ,
        0.14899968, 0.08880062, 0.12200044, 0.11602267, 0.07659773]],
      dtype=float32)

In [19]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [20]:
loss_fn(y_train[:1], predictions).numpy()

1.9038111

In [21]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [22]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 872us/step - loss: 0.2983 - accuracy: 0.9125
Epoch 2/5
1875/1875 [==============================] - 2s 835us/step - loss: 0.1440 - accuracy: 0.9575
Epoch 3/5
1875/1875 [==============================] - 2s 837us/step - loss: 0.1083 - accuracy: 0.9669
Epoch 4/5
1875/1875 [==============================] - 2s 846us/step - loss: 0.0866 - accuracy: 0.9731
Epoch 5/5
1875/1875 [==============================] - 2s 865us/step - loss: 0.0749 - accuracy: 0.9767


In [23]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0702 - accuracy: 0.9779 - 253ms/epoch - 808us/step


[0.07018530368804932, 0.9779000282287598]

In [24]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [25]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.7515065e-07, 2.1401743e-08, 5.1216398e-06, 1.6590323e-04,
        1.6983834e-11, 2.0330830e-07, 7.6137750e-15, 9.9982685e-01,
        1.5799277e-07, 1.5405561e-06],
       [5.2786999e-07, 3.4142280e-04, 9.9960476e-01, 3.6838828e-05,
        3.8785160e-12, 1.8012660e-06, 1.7955667e-06, 5.2207266e-12,
        1.2939997e-05, 8.0611030e-12],
       [1.6375942e-08, 9.9961436e-01, 4.5716253e-05, 4.0786726e-06,
        2.1901349e-05, 6.3714315e-06, 9.8599503e-06, 1.7143390e-04,
        1.2599258e-04, 3.1319976e-07],
       [9.9993932e-01, 6.5517064e-10, 3.9156130e-05, 6.3895506e-08,
        9.0748379e-08, 6.5429685e-07, 3.8576372e-06, 1.5859678e-05,
        9.4925108e-09, 9.2074441e-07],
       [8.5068401e-05, 4.4968609e-10, 3.1145002e-05, 6.1157785e-08,
        9.9734193e-01, 4.1925477e-06, 2.9678185e-05, 6.6483175e-05,
        9.0023086e-06, 2.4322907e-03]], dtype=float32)>